/**
 * Biochat Plan B: Arxiv Plugin Adapter
 * Converts LobeChat's arxiv plugin → Nexu Skill
 * 
 * LobeChat arxiv plugin: searches academic papers from arxiv.org
 * Nexu execution: uses arxiv API via curl, parses XML results
 */

export interface ArxivPaper {
  title: string;
  authors: string[];
  abstract: string;
  pdfUrl: string;
  published: string;
  categories: string[];
}

export class ArxivAdapter {
  private readonly ARXIV_API = 'http://export.arxiv.org/api/query';

  /**
   * Search arxiv by keyword
   */
  async search(query: string, maxResults = 10): Promise<ArxivPaper[]> {
    const url = `${this.ARXIV_API}?search_query=all:${encodeURIComponent(query)}&start=0&max_results=${maxResults}&sortBy=relevance&sortOrder=descending`;
    
    const { execSync } = require('child_process');
    const xml = execSync(`curl -s "${url}"`, { encoding: 'utf-8' });
    
    return this.parseAtom(xml);
  }

  private parseAtom(xml: string): ArxivPaper[] {
    // Simple XML parsing without external dependencies
    const papers: ArxivPaper[] = [];
    const entries = xml.split('<entry>');
    
    for (let i = 1; i < entries.length; i++) {
      const e = entries[i];
      papers.push({
        title: this.extract(e, '<title>'),
        authors: this.extractAll(e, '<author>', '<name>'),
        abstract: this.extract(e, '<summary>').replace(/\n/g, ' ').trim(),
        pdfUrl: this.extract(e, '<link title="pdf"').replace('href="', '').replace('"', ''),
        published: this.extract(e, '<published>'),
        categories: this.extractAll(e, '<category', 'term=').map((c: string) => c.replace(/"/g, '')),
      });
    }
    return papers;
  }

  private extract(xml: string, tag: string): string {
    const idx = xml.indexOf(tag);
    if (idx === -1) return '';
    const start = idx + tag.length;
    const end = xml.indexOf('<', start);
    return xml.slice(start, end).trim();
  }

  private extractAll(xml: string, outer: string, inner: string): string[] {
    const results: string[] = [];
    let idx = 0;
    while (true) {
      idx = xml.indexOf(outer, idx);
      if (idx === -1) break;
      const start = idx + outer.length;
      const end = xml.indexOf('<', start);
      const block = xml.slice(start, end);
      const nameIdx = block.indexOf(inner);
      if (nameIdx !== -1) {
        const nameStart = nameIdx + inner.length;
        const nameEnd = block.indexOf('<', nameStart);
        results.push(block.slice(nameStart, nameEnd).trim());
      }
      idx++;
    }
    return results;
  }

  /**
   * Generate Nexu Skill SKILL.md for this adapter
   */
  generateSkillMd(): string {
    return `---
name: lobe-arxiv
description: Search academic papers from arxiv.org. Use when the user asks to find papers, research, or academic articles about a topic. Triggers: "search arxiv", "find papers on X", "latest research on Y", "academic paper search".
---

# Arxiv Academic Paper Search

This skill searches arxiv.org for academic papers using the \`ArxivAdapter\`.

## Usage

\`\`\`typescript
const adapter = new ArxivAdapter();
const papers = await adapter.search('transformer attention mechanism', 10);
papers.forEach(p => console.log(p.title, p.pdfUrl));
\`\`\`

## Output Format

Each paper returns:
- **title**: Paper title
- **authors**: Array of author names  
- **abstract**: Paper abstract (truncated)
- **pdfUrl**: Direct PDF download link
- **published**: Publication date
- **categories**: arxiv subject categories

## Notes

- Max 100 results per query
- Uses arxiv's OpenSearch API (no API key required)
- Abstracts are truncated to ~300 chars for display
- Sorted by relevance by default

---
*Auto-generated by Biochat Plan B Adapter*
`;
  }
}
