/**
 * Biochat Plan B: File Tool Adapter
 * Converts LobeChat's file operations plugin → Nexu Skill
 * 
 * Local file operations: read, write, list, delete, glob, stat
 */

import { readFileSync, writeFileSync, readdirSync, statSync, unlinkSync, existsSync } from 'fs';
import { join, basename, extname } from 'path';

export interface FileEntry {
  name: string;
  path: string;
  type: 'file' | 'directory' | 'symlink';
  size: number;
  modified: string;
}

export class FileToolAdapter {
  private basePath: string;

  constructor(basePath = process.env.BIOCHAT_FILE_SCOPE || '/tmp/biochat-files') {
    this.basePath = basePath;
  }

  async read(path: string, options?: { encoding?: 'utf-8' | 'binary'; limit?: number }): Promise<string | Buffer> {
    const fullPath = this.resolve(path);
    const content = readFileSync(fullPath, options?.encoding === 'utf-8' ? 'utf-8' : undefined);
    if (options?.limit && content.length > options.limit) {
      return content.slice(0, options.limit) + '\n... [truncated]';
    }
    return content;
  }

  async write(path: string, content: string): Promise<{ success: boolean; bytes: number }> {
    const fullPath = this.resolve(path);
    const dir = basename(fullPath);
    writeFileSync(fullPath, content, 'utf-8');
    return { success: true, bytes: content.length };
  }

  async list(dir: string, options?: { recursive?: boolean }): Promise<FileEntry[]> {
    const fullPath = this.resolve(dir);
    const entries = readdirSync(fullPath);
    const results: FileEntry[] = [];

    for (const name of entries) {
      const entryPath = join(fullPath, name);
      try {
        const stat = statSync(entryPath);
        results.push({
          name,
          path: entryPath,
          type: stat.isDirectory() ? 'directory' : stat.isSymbolicLink() ? 'symlink' : 'file',
          size: stat.size,
          modified: stat.mtime.toISOString(),
        });
        if (options?.recursive && stat.isDirectory()) {
          const sub = await this.list(entryPath, { recursive: true });
          results.push(...sub);
        }
      } catch {
        // skip inaccessible files
      }
    }
    return results;
  }

  async delete(path: string): Promise<{ success: boolean }> {
    const fullPath = this.resolve(path);
    if (!existsSync(fullPath)) return { success: false };
    unlinkSync(fullPath);
    return { success: true };
  }

  async stat(path: string): Promise<FileEntry | null> {
    const fullPath = this.resolve(path);
    if (!existsSync(fullPath)) return null;
    const stat = statSync(fullPath);
    return {
      name: basename(fullPath),
      path: fullPath,
      type: stat.isDirectory() ? 'directory' : 'file',
      size: stat.size,
      modified: stat.mtime.toISOString(),
    };
  }

  async glob(pattern: string): Promise<string[]> {
    const { execSync } = require('child_process');
    const base = this.basePath;
    try {
      const out = execSync(`find ${base} -name "${pattern}" 2>/dev/null`, { encoding: 'utf-8' });
      return out.split('\n').filter(Boolean);
    } catch {
      return [];
    }
  }

  /**
   * Resolve path with scope audit (prevent path traversal)
   */
  private resolve(path: string): string {
    const full = join(this.basePath, path);
    if (!full.startsWith(this.basePath)) {
      throw new Error(`Path traversal denied: ${path} is outside scope`);
    }
    return full;
  }

  generateSkillMd(): string {
    return `---
name: lobe-file-tool
description: Perform local file operations (read, write, list, delete, stat, glob). Use when the user asks to read a file, write content to a file, list directory contents, delete a file, or find files by pattern. Triggers: "read file X", "write to file", "list files in folder", "delete file", "find files matching pattern".
---

# Local File Operations Skill

File read/write/list/delete via the \`FileToolAdapter\`.

## Security

All paths are scoped to \`BIOCHAT_FILE_SCOPE\` (default: \`/tmp/biochat-files\`).
Path traversal attacks are blocked.

## Usage

\`\`\`typescript
const adapter = new FileToolAdapter('/path/to/scope');

// Read
const content = await adapter.read('notes.txt', { encoding: 'utf-8', limit: 5000 });

// Write  
await adapter.write('output.txt', 'Hello Biochat!');

// List
const files = await adapter.list('.', { recursive: false });

// Stat
const info = await adapter.stat('data.json');

// Glob
const matches = await adapter.glob('*.pdf');

// Delete
await adapter.delete('temp.txt');
\`\`\`

## Environment

- \`BIOCHAT_FILE_SCOPE\`: Root directory for file operations (default: \`/tmp/biochat-files\`)

---
*Auto-generated by Biochat Plan B Adapter*
`;
  }
}
