/**
 * Biochat Plan B: Search Engine Adapter  
 * Converts LobeChat's web search plugin → Nexu Skill
 * 
 * Uses Brave Search API (or Google) for web search
 */

export interface SearchResult {
  title: string;
  url: string;
  description: string;
  published?: string;
}

export class SearchEngineAdapter {
  // Uses Brave's free search API (no key required for limited use)
  private readonly BRAVE_SEARCH = 'https://api.search.brave.com/res/v1/web/search';
  private apiKey?: string;

  constructor(apiKey?: string) {
    this.apiKey = apiKey || process.env.BRAVE_SEARCH_KEY;
  }

  /**
   * Search the web
   */
  async search(query: string, count = 10): Promise<SearchResult[]> {
    const { execSync } = require('child_process');
    
    const safeQuery = encodeURIComponent(query);
    let url = `${this.BRAVE_SEARCH}?q=${safeQuery}&count=${count}`;
    
    const cmd = this.apiKey
      ? `curl -s "${url}" -H "Accept: application/json" -H "X-Subscription-Token: ${this.apiKey}"`
      : `curl -s "https://html.duckduckgo.com/html/?q=${safeQuery}"`;

    const raw = execSync(cmd, { encoding: 'utf-8', timeout: 10000 });
    
    if (this.apiKey) {
      return this.parseBraveJson(raw);
    }
    return this.parseDuckDuckGoHtml(raw);
  }

  private parseBraveJson(json: string): SearchResult[] {
    try {
      const data = JSON.parse(json);
      return (data.web?.results || []).map((r: any) => ({
        title: r.title,
        url: r.url,
        description: r.description,
        published: r.age || undefined,
      }));
    } catch {
      return [];
    }
  }

  private parseDuckDuckGoHtml(html: string): SearchResult[] {
    // Parse DuckDuckGo HTML results
    const results: SearchResult[] = [];
    const regex = /<a class="result__a" href="([^"]+)">([^<]+)<\/a>[\s\S]*?<a class="result__snippet"[^>]*>([\s\S]*?) <\/a>/g;
    let match;
    while ((match = regex.exec(html)) !== null && results.length < 10) {
      results.push({
        url: match[1],
        title: match[2].trim(),
        description: match[3].replace(/<[^>]+>/g, '').trim(),
      });
    }
    return results;
  }

  generateSkillMd(): string {
    return `---
name: lobe-search
description: Search the web for information. Use when the user asks to search for something online, look up information, find recent news about X, or Google something. Triggers: "search for X", "look up", "Google", "web search", "find information about".
---

# Web Search Skill

Search the web using Brave Search API or DuckDuckGo fallback.

## Usage

\`\`\`typescript
const adapter = new SearchEngineAdapter(process.env.BRAVE_SEARCH_KEY);
const results = await adapter.search('latest AI news', 10);
results.forEach(r => console.log(r.title, r.url));
\`\`\`

## Environment

- \`BRAVE_SEARCH_KEY\`: Optional Brave Search API key (falls back to DuckDuckGo HTML if not set)

## Output

Returns array of \`SearchResult\`: \`{ title, url, description, published? }\`

---
*Auto-generated by Biochat Plan B Adapter*
`;
  }
}
