/**
 * Biochat Plan B: LobeChat Plugin → Nexu Skill Adapter
 * 
 * Converts LobeChat's manifest.json-based plugins into Nexu-compatible Skills.
 * 
 * LobeChat Plugin Manifest Reference:
 * https://github.com/lobehub/lobe-chat/tree/main/packages/plugin-sdk
 * 
 * Nexu Skill Format:
 * SKILL.md with YAML frontmatter (name, description) + Markdown body
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

// ============================================================
// LobeChat Plugin Manifest Schema (known fields)
// ============================================================
// interface LobePluginManifest {
//   name: string;           // e.g. "arxiv-search"
//   version: string;        // e.g. "1.0.0"
//   description: string;
//   author: string;
//   tags: string[];
//   gateway: string;        // URL to the plugin's HTTP gateway
//   api: {
//     protocol: 'http' | 'https' | 'websocket';
//     name: string;
//   };
//   functions: LobeFunction[];
// }

// interface LobeFunction {
//   name: string;
//   description: string;
//   parameters?: {
//     type: 'object';
//     properties: Record<string, any>;
//     required?: string[];
//   };
// }

// ============================================================
// Nexu Skill Frontmatter Schema
// ============================================================
// ---
// name: skill-name
// description: When the user asks about X, use this skill. Triggers: ...
// ---

// ============================================================
// Core Adapter Class
// ============================================================

export class LobePluginAdapter {
  private manifest: any;
  private pluginName: string;
  private outputDir: string;

  constructor(manifestPath: string, outputDir: string) {
    this.manifest = JSON.parse(readFileSync(manifestPath, 'utf-8'));
    this.pluginName = this.manifest.name.replace(/[^a-z0-9-_]/gi, '-').toLowerCase();
    this.outputDir = outputDir;
  }

  /**
   * Convert a LobeChat plugin manifest to a Nexu-compatible Skill
   */
  convert(): void {
    const skillDir = join(this.outputDir, `lobe-${this.pluginName}`);
    mkdirSync(skillDir, { recursive: true });

    // 1. Generate SKILL.md
    const skillMd = this.generateSkillMd();
    writeFileSync(join(skillDir, 'SKILL.md'), skillMd, 'utf-8');

    // 2. Generate references/gateway.md with API details
    const gatewayMd = this.generateGatewayMd();
    mkdirSync(join(skillDir, 'references'), { recursive: true });
    writeFileSync(join(skillDir, 'references', 'gateway.md'), gatewayMd, 'utf-8');

    // 3. Generate scripts/bridge.sh to call the Lobe plugin gateway
    const bridgeSh = this.generateBridgeScript();
    mkdirSync(join(skillDir, 'scripts'), { recursive: true });
    writeFileSync(join(skillDir, 'scripts', 'call-gateway.sh'), bridgeSh, 'utf-8');

    console.log(`[Biochat] Converted Lobe plugin "${this.manifest.name}" → Nexu Skill at ${skillDir}`);
  }

  private generateSkillMd(): string {
    const funcList = (this.manifest.functions || [])
      .map((f: any) => `- **${f.name}**: ${f.description}`)
      .join('\n');

    const frontmatter = `---
name: lobe-${this.pluginName}
description: Nexu Skill adapter for LobeChat plugin "${this.manifest.name}".
  Provides access to: ${this.manifest.description}.
  Use when: user asks to ${this.manifest.functions?.map((f: any) => f.name).join(', ') || 'use this plugin'}.
  Triggers: ${this.manifest.tags?.map((t: string) => `"${t}"`).join(', ') || 'plugin execution, gateway call'}.
---

`;

    const body = `# LobeChat Plugin: ${this.manifest.name}

## Overview

This is a Nexu Skill adapter wrapping the LobeChat plugin **${this.manifest.name}** (v${this.manifest.version}) by ${this.manifest.author}.

**Original Description:** ${this.manifest.description}

## Available Functions

${funcList || '*(no explicit functions defined — check gateway.md)*'}

## Usage Pattern

When the user triggers this skill, use the bridge script to call the plugin gateway:

\`\`\`bash
bash scripts/call-gateway.sh <function_name> <args_json>
\`\`\`

For detailed gateway specs, see [references/gateway.md](references/gateway.md).

## Notes

- Plugin gateway: \`${this.manifest.gateway || 'N/A'}\`
- API protocol: \`${this.manifest.api?.protocol || 'N/A'}\`
- Auto-generated by Biochat Plan B Adapter (${new Date().toISOString()})
`;

    return frontmatter + body;
  }

  private generateGatewayMd(): string {
    return `# ${this.manifest.name} — Gateway Reference

## Plugin Info
- **Version:** ${this.manifest.version}
- **Author:** ${this.manifest.author}
- **Gateway URL:** \`${this.manifest.gateway || 'not specified'}\`
- **API Protocol:** \`${this.manifest.api?.protocol || 'N/A'}\`

## Functions
${(this.manifest.functions || []).map((f: any) => `### ${f.name}

${f.description}

${f.parameters ? `**Parameters:**
\`\`\`json
${JSON.stringify(f.parameters, null, 2)}
\`\`\`` : ''}`).join('\n\n')}

---
*Auto-generated by Biochat Plan B Adapter*
`;
  }

  private generateBridgeScript(): string {
    const gateway = this.manifest.gateway || 'http://localhost:8080';
    return `#!/bin/bash
# Biochat Plan B — Lobe Plugin Gateway Bridge
# Plugin: ${this.manifest.name}
# Gateway: ${gateway}

FUNCTION_NAME=$1
ARGS_JSON=$2

if [ -z "$FUNCTION_NAME" ]; then
  echo "Usage: call-gateway.sh <function_name> [args_json]"
  exit 1
fi

PAYLOAD=$(cat <<EOF
{
  "name": "$FUNCTION_NAME",
  "arguments": ${ARGS_JSON:-'{}'}
}
EOF
)

curl -s -X POST "${gateway}/api functions/${this.manifest.api?.name || 'invoke'}" \\
  -H "Content-Type: application/json" \\
  -d "$PAYLOAD"
`;
  }

  /**
   * Batch convert all plugins in a directory
   */
  static batchConvert(pluginsDir: string, outputDir: string): void {
    const entries = require('fs').readdirSync(pluginsDir);
    const manifests = entries.filter((f: string) => f === 'manifest.json');
    
    for (const manifestPath of manifests) {
      try {
        const adapter = new LobePluginAdapter(manifestPath, outputDir);
        adapter.convert();
      } catch (err) {
        console.error(`[Biochat] Failed to convert ${manifestPath}:`, err);
      }
    }
  }
}

// CLI entry point
const [,, manifestPath, outputDir] = process.argv;
if (manifestPath && outputDir) {
  const adapter = new LobePluginAdapter(manifestPath, outputDir);
  adapter.convert();
}
